[phases.build]
nixPkgs = ["...", "unzip"] # Install the unzip package from Nix
cmds = ["...", "unzip target/ddex-message-validator*.zip -d build/"] # Unzip the DDEX message validator

[start]
cmd = "cd build/*/bin && ./start-api"
